<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-02-13">

<title>IS415-GAA - Take-Home Exercise 2: Spatio-temporal analysis of COVID-19 Vaccination Trends at the Sub-district Level, DKI Jarkarta</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex07/In-class_Ex07.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html">
 <span class="dropdown-text">Take-Home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html">
 <span class="dropdown-text">Take-Home Exercise 2</span></a>
  </li>  
        <li class="dropdown-header">Take-Home Exercise 3</li>
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/junhao2309/IS415"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About Me</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#context" id="toc-context" class="nav-link active" data-scroll-target="#context"><span class="toc-section-number">1</span>  Context</a></li>
  <li><a href="#the-set-up" id="toc-the-set-up" class="nav-link" data-scroll-target="#the-set-up"><span class="toc-section-number">2</span>  The Set Up</a>
  <ul class="collapse">
  <li><a href="#packages-used" id="toc-packages-used" class="nav-link" data-scroll-target="#packages-used"><span class="toc-section-number">2.1</span>  Packages Used</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="toc-section-number">2.2</span>  The Data</a></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="toc-section-number">3</span>  Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#geospatial-data" id="toc-geospatial-data" class="nav-link" data-scroll-target="#geospatial-data"><span class="toc-section-number">3.1</span>  Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#import-geospatial-data" id="toc-import-geospatial-data" class="nav-link" data-scroll-target="#import-geospatial-data"><span class="toc-section-number">3.1.1</span>  Import Geospatial Data</a></li>
  <li><a href="#check-for-invalid-geometries" id="toc-check-for-invalid-geometries" class="nav-link" data-scroll-target="#check-for-invalid-geometries"><span class="toc-section-number">3.1.2</span>  Check for invalid geometries</a></li>
  <li><a href="#check-for-missing-values" id="toc-check-for-missing-values" class="nav-link" data-scroll-target="#check-for-missing-values"><span class="toc-section-number">3.1.3</span>  Check for Missing values</a></li>
  <li><a href="#check-coordinate-system" id="toc-check-coordinate-system" class="nav-link" data-scroll-target="#check-coordinate-system"><span class="toc-section-number">3.1.4</span>  Check Coordinate System</a></li>
  <li><a href="#removing-outer-islands" id="toc-removing-outer-islands" class="nav-link" data-scroll-target="#removing-outer-islands"><span class="toc-section-number">3.1.5</span>  Removing Outer Islands</a></li>
  </ul></li>
  <li><a href="#aspatial-data" id="toc-aspatial-data" class="nav-link" data-scroll-target="#aspatial-data"><span class="toc-section-number">3.2</span>  Aspatial Data</a>
  <ul class="collapse">
  <li><a href="#import-aspatial-data" id="toc-import-aspatial-data" class="nav-link" data-scroll-target="#import-aspatial-data"><span class="toc-section-number">3.2.1</span>  Import Aspatial Data</a></li>
  <li><a href="#columns-of-interest-and-its-translation" id="toc-columns-of-interest-and-its-translation" class="nav-link" data-scroll-target="#columns-of-interest-and-its-translation"><span class="toc-section-number">3.2.2</span>  Columns of interest and its translation</a></li>
  <li><a href="#mutate-aspatial-data" id="toc-mutate-aspatial-data" class="nav-link" data-scroll-target="#mutate-aspatial-data"><span class="toc-section-number">3.2.3</span>  Mutate Aspatial Data</a></li>
  </ul></li>
  <li><a href="#combining-geospatial-and-aspatial-together" id="toc-combining-geospatial-and-aspatial-together" class="nav-link" data-scroll-target="#combining-geospatial-and-aspatial-together"><span class="toc-section-number">3.3</span>  Combining Geospatial and Aspatial together</a></li>
  </ul></li>
  <li><a href="#choropleth-mapping-and-analysis" id="toc-choropleth-mapping-and-analysis" class="nav-link" data-scroll-target="#choropleth-mapping-and-analysis"><span class="toc-section-number">4</span>  Choropleth Mapping and Analysis</a>
  <ul class="collapse">
  <li><a href="#visualizing-the-data" id="toc-visualizing-the-data" class="nav-link" data-scroll-target="#visualizing-the-data"><span class="toc-section-number">4.1</span>  Visualizing the data</a>
  <ul class="collapse">
  <li><a href="#r-shiny" id="toc-r-shiny" class="nav-link" data-scroll-target="#r-shiny"><span class="toc-section-number">4.1.1</span>  R Shiny</a></li>
  <li><a href="#tmap-visualization" id="toc-tmap-visualization" class="nav-link" data-scroll-target="#tmap-visualization"><span class="toc-section-number">4.1.2</span>  Tmap Visualization</a></li>
  </ul></li>
  <li><a href="#spatial-patterns-observed-200words" id="toc-spatial-patterns-observed-200words" class="nav-link" data-scroll-target="#spatial-patterns-observed-200words"><span class="toc-section-number">4.2</span>  Spatial Patterns observed (200words)</a></li>
  </ul></li>
  <li><a href="#local-gi-analysis" id="toc-local-gi-analysis" class="nav-link" data-scroll-target="#local-gi-analysis"><span class="toc-section-number">5</span>  Local Gi* Analysis</a>
  <ul class="collapse">
  <li><a href="#computing-contiguity-spatial-weights" id="toc-computing-contiguity-spatial-weights" class="nav-link" data-scroll-target="#computing-contiguity-spatial-weights"><span class="toc-section-number">5.1</span>  Computing Contiguity Spatial Weights</a></li>
  <li><a href="#row-standardised-weights-matrix" id="toc-row-standardised-weights-matrix" class="nav-link" data-scroll-target="#row-standardised-weights-matrix"><span class="toc-section-number">5.2</span>  Row-standardised weights matrix</a></li>
  <li><a href="#moran-i-test" id="toc-moran-i-test" class="nav-link" data-scroll-target="#moran-i-test"><span class="toc-section-number">5.3</span>  Moran I Test</a>
  <ul class="collapse">
  <li><a href="#statistical-conclusion-not-more-than-250words" id="toc-statistical-conclusion-not-more-than-250words" class="nav-link" data-scroll-target="#statistical-conclusion-not-more-than-250words"><span class="toc-section-number">5.3.1</span>  Statistical Conclusion (Not more than 250words) :</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"><span class="toc-section-number">5.3.2</span>  </a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-Home Exercise 2: Spatio-temporal analysis of COVID-19 Vaccination Trends at the Sub-district Level, DKI Jarkarta</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 13, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">February 20, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="context" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Context</h1>
<p>Since the outbreak of COVID-19, many countries have rushed to create a vaccine and ensure its population is well immunized against this novel coronavirus. On 13 January 2021, the mass immunisation program commenced and since then Indonesia ranks third in Asia and fifth in the world in terms of total doses given.</p>
<p>In this take-home assignment, we will be exploring vaccination rates in DKI Jarkarta, identifying sub-districts with relatively higher number of vaccination rate and how they changed over time.</p>
<p>The tasks given to us is as follows:</p>
<p><strong>Choropleth Mapping and Analysis</strong></p>
<ul>
<li><p>Compute the monthly vaccination rate from July 2021 to June 2022 at sub-district (also known as kelurahan in Bahasa Indonesia) level,</p></li>
<li><p>Prepare the monthly vaccination rate maps by using appropriate tmap functions,</p></li>
<li><p>Describe the spatial patterns revealed by the choropleth maps (not more than 200 words).</p></li>
</ul>
<p><strong>Local Gi* Analysis</strong></p>
<p>With reference to the vaccination rate maps prepared in ESDA:</p>
<ul>
<li><p>Compute local Gi* values of the monthly vaccination rate,</p></li>
<li><p>Display the Gi* maps of the monthly vaccination rate. The maps should only display the significant (i.e.&nbsp;p-value &lt; 0.05)</p></li>
<li><p>With reference to the analysis results, draw statistical conclusions (not more than 250 words).</p></li>
</ul>
<p><strong>Emerging Hot Spot Analysis(EHSA)</strong></p>
<p>With reference to the local Gi* values of the vaccination rate maps prepared in the previous section:</p>
<ul>
<li><p>Perform Mann-Kendall Test by using the spatio-temporal local Gi* values,</p></li>
<li><p>Select three sub-districts and describe the temporal trends revealed (not more than 250 words), and</p></li>
<li><p>Prepared a EHSA map of the Gi* values of vaccination rate. The maps should only display the significant (i.e.&nbsp;p-value &lt; 0.05).</p></li>
<li><p>With reference to the EHSA map prepared, describe the spatial patterns revelaed. (not more than 250 words).</p></li>
</ul>
<p>Throughout this page, each step will be explained and guided so that you can follow along.</p>
</section>
<section id="the-set-up" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> The Set Up</h1>
<section id="packages-used" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="packages-used"><span class="header-section-number">2.1</span> Packages Used</h2>
<p>The R packages used for this analysis are:</p>
<ul>
<li><p>sf</p></li>
<li><p>tidyverse</p></li>
<li><p>spatstat</p></li>
<li><p>tmap</p></li>
<li><p>sfdep</p></li>
<li><p>maptools</p></li>
<li><p>readxl</p></li>
</ul>
<p>The code chunk below checks whether the packages have been installed, if not it will automatically install them and load the packages into Rstudio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, raster, spatstat, tmap, tidyverse, sfdep, maptools, readxl, spdep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-data" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="the-data"><span class="header-section-number">2.2</span> The Data</h2>
<table class="table">
<thead>
<tr class="header">
<th>Type</th>
<th>Name</th>
<th>Format</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geospatial</td>
<td><a href="https://www.indonesia-geospasial.com/2020/04/download-shapefile-shp-batas-desa.html">Batas Desa Provinsi DKI Jakarta</a></td>
<td>shapefile</td>
<td>Sub-districts in DKI Jakarta</td>
</tr>
<tr class="even">
<td>Aspatial</td>
<td><a href="https://riwayat-file-vaksinasi-dki-jakarta-jakartagis.hub.arcgis.com/">Riwayat File Vaksinasi DKI Jakarta</a></td>
<td>.xlsx</td>
<td>Sub-district level data of vaccination numbers between July 2021 to June 2022</td>
</tr>
</tbody>
</table>
<ul>
<li>Geospatial Data</li>
</ul>
<p>The link under Geospatial Data above brings you to a page where there are many download links sorted by province. Ensure that you are using <strong>Shapefile (SHP) Batas Desa Provinsi DKI Jakarta.</strong></p>
<ul>
<li>Aspatial Data</li>
</ul>
<p>The link under Aspatial Data above brings you to a page where there are two types of data files you can use. Please choose <strong>Data Vaksinasi Berbasis Kelurahan dan Kecamatan</strong> and download a total of 12 files beginning July 2021 to June 2022.</p>
<p>Do note that we will be using the beginning of each month for our download.</p>
</section>
</section>
<section id="data-wrangling" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data Wrangling</h1>
<section id="geospatial-data" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="geospatial-data"><span class="header-section-number">3.1</span> Geospatial Data</h2>
<section id="import-geospatial-data" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="import-geospatial-data"><span class="header-section-number">3.1.1</span> Import Geospatial Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>geoDKI <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">layer =</span> <span class="st">"BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA' from data source 
  `/Users/junhaoteo/Documents/junhao2309/IS415/Take-Home_Ex/Take-Home_Ex02/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 269 features and 161 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 106.3831 ymin: -6.370815 xmax: 106.9728 ymax: -5.184322
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>From the output above, we can see that the data set has a geometry type, Multipolygon, and has 269 features and 161 fields.</p>
</section>
<section id="check-for-invalid-geometries" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="check-for-invalid-geometries"><span class="header-section-number">3.1.2</span> Check for invalid geometries</h3>
<p>Before we begin, we should check whether there are any invalid geometries by using the code chunk below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_is_valid</span>(geoDKI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [76] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [91] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[106] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[121] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[136] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[151] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[166] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[181] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[196] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[211] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[226] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[241] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[256] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE</code></pre>
</div>
</div>
<p>st_is_valid() from the sf package helps to check whether a geometry is valid. From the output, there are no invalid geometries.</p>
</section>
<section id="check-for-missing-values" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="check-for-missing-values"><span class="header-section-number">3.1.3</span> Check for Missing values</h3>
<p>The code chunk below uses is.na() from base R checks whether the data set has NA values. which() from base R takes the indices of these values and lastly length() helps us calculate the length of the data objects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">is.na</span>(geoDKI) <span class="sc">==</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14</code></pre>
</div>
</div>
<p>In the above output, there are 14 NA values within the jakarta data set.</p>
<p>To remove them, we can simply use na.exclude to delete the rows with NA values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>geoDKI <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(geoDKI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can run the same code to see whether all NA values have been removed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">is.na</span>(geoDKI) <span class="sc">==</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Nice! All NA values have been removed.</p>
</section>
<section id="check-coordinate-system" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="check-coordinate-system"><span class="header-section-number">3.1.4</span> Check Coordinate System</h3>
<p>As different countries use different projection systems, we need to first check the CRS of jakarta.</p>
<p>The code chunk below uses st_crs() from the sf package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(geoDKI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>We notice that jakarta is using EPSG::4326 which is the wrong projection coordinate system. DKI Jakarta uses the DGN95, the ‘Datum Geodesi Nasional 1995’, EPSG::23878</p>
<p>We can transform the crs by using st_transform() from the sf package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>geoDKI <span class="ot">&lt;-</span> geoDKI <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">23878</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(geoDKI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:23878 
  wkt:
PROJCRS["DGN95 / UTM zone 48S",
    BASEGEOGCRS["DGN95",
        DATUM["Datum Geodesi Nasional 1995",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4755]],
    CONVERSION["UTM zone 48S",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",105,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",10000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Indonesia - south of equator and between 102°E and 108°E - onshore and offshore."],
        BBOX[-10.73,102,0,108.01]],
    ID["EPSG",23878]]</code></pre>
</div>
</div>
<p>From the output above, we can see that the CRS has been properly assigned.</p>
</section>
<section id="removing-outer-islands" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="removing-outer-islands"><span class="header-section-number">3.1.5</span> Removing Outer Islands</h3>
<p>Let us visualise the geographical polygons.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qtm</span>(geoDKI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see from the output that jakarta includes both the mainland and the outer islands. Our study area focuses only on the mainland and thus we need to remove them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(geoDKI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before we continue further, we need to understand how DKI Jakarta geographical regions are segmented. The code chunk above lets you view the entire dataset. Let us understand the key variables below:</p>
<p>With the help of uncle google, we will translate the names.</p>
<table class="table">
<thead>
<tr class="header">
<th>Name</th>
<th>Translation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>KODE_DESA</td>
<td>Village Code</td>
</tr>
<tr class="even">
<td>DESA</td>
<td>Village</td>
</tr>
<tr class="odd">
<td>PROVINSI</td>
<td>Province</td>
</tr>
<tr class="even">
<td>KAB_KOTA</td>
<td>City</td>
</tr>
<tr class="odd">
<td>KECAMATAN</td>
<td>District</td>
</tr>
<tr class="even">
<td>DESA_KELUR</td>
<td>Sub-District</td>
</tr>
</tbody>
</table>
<p>KAB_KOTA would be the most logical choice in isolating out the outer islands.</p>
<p>The code chunk below helps to output uniques values in KAB_KOTA field.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(geoDKI<span class="sc">$</span>KAB_KOTA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "JAKARTA BARAT"    "JAKARTA PUSAT"    "KEPULAUAN SERIBU" "JAKARTA UTARA"   
[5] "JAKARTA TIMUR"    "JAKARTA SELATAN" </code></pre>
</div>
</div>
<p>The output above shows that there are 6 major cities in DKI Jakarta.</p>
<p>The codechunk below will visualize the data with respect to the 6 major cities. We can then see which city isolates out the outer islands.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(geoDKI) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"KAB_KOTA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the visualization above, we can see that KEPULAUAN SERIBU is not part of the mainland. We can then use filter() from dplyr package to remove the outer islands.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>geoDKI <span class="ot">&lt;-</span> <span class="fu">filter</span>(geoDKI, KAB_KOTA <span class="sc">!=</span><span class="st">"KEPULAUAN SERIBU"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qtm</span>(geoDKI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now we can see that our shapefile only contains the mainland, which is our study area.</p>
<p>Now, before we move on, geoDKI has alot of columns, we will select those that are relevant to our analysis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>geoDKI <span class="ot">&lt;-</span> geoDKI <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="aspatial-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="aspatial-data"><span class="header-section-number">3.2</span> Aspatial Data</h2>
<section id="import-aspatial-data" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="import-aspatial-data"><span class="header-section-number">3.2.1</span> Import Aspatial Data</h3>
<p>Before we import the data in, the file names are rather long. First, go to your data folder and change the aspatial data file names to Y-M format. It would look like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1137647241.png" class="img-fluid figure-img" width="488"></p>
</figure>
</div>
<p>There are a total of 12 excel files we need to load into Rstudio. To read the files more efficiently, we will use the “for loop” function to read all the excel files into a data frame by using the read_excel() from the readxl package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the working directory to the folder containing the Excel files</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"data/aspatial/"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a list of all Excel files in the directory</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>aspatial_data <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">pattern =</span> <span class="st">".xlsx"</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through the files and read each one into a data frame</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> aspatial_data) {</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">assign</span>(<span class="fu">gsub</span>(<span class="st">".xlsx"</span>, <span class="st">""</span>, i), <span class="fu">read_excel</span>(i))</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="columns-of-interest-and-its-translation" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="columns-of-interest-and-its-translation"><span class="header-section-number">3.2.2</span> Columns of interest and its translation</h3>
<p>In the aspatial data set, what we want is the total vaccination and not vaccinated numbers, along with these 4 regional classification columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="st">`</span><span class="at">2022-6</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "KODE KELURAHAN"                            
 [2] "WILAYAH KOTA"                              
 [3] "KECAMATAN"                                 
 [4] "KELURAHAN"                                 
 [5] "SASARAN"                                   
 [6] "BELUM VAKSIN"                              
 [7] "JUMLAH\r\nDOSIS 1"                         
 [8] "JUMLAH\r\nDOSIS 2"                         
 [9] "JUMLAH\r\nDOSIS 3"                         
[10] "TOTAL VAKSIN\r\nDIBERIKAN"                 
[11] "LANSIA\r\nDOSIS 1"                         
[12] "LANSIA\r\nDOSIS 2"                         
[13] "LANSIA\r\nDOSIS 3"                         
[14] "LANSIA TOTAL \r\nVAKSIN DIBERIKAN"         
[15] "PELAYAN PUBLIK\r\nDOSIS 1"                 
[16] "PELAYAN PUBLIK\r\nDOSIS 2"                 
[17] "PELAYAN PUBLIK\r\nDOSIS 3"                 
[18] "PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN"  
[19] "GOTONG ROYONG\r\nDOSIS 1"                  
[20] "GOTONG ROYONG\r\nDOSIS 2"                  
[21] "GOTONG ROYONG\r\nDOSIS 3"                  
[22] "GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN"   
[23] "TENAGA KESEHATAN\r\nDOSIS 1"               
[24] "TENAGA KESEHATAN\r\nDOSIS 2"               
[25] "TENAGA KESEHATAN\r\nDOSIS 3"               
[26] "TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN"
[27] "TAHAPAN 3\r\nDOSIS 1"                      
[28] "TAHAPAN 3\r\nDOSIS 2"                      
[29] "TAHAPAN 3\r\nDOSIS 3"                      
[30] "TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN"       
[31] "REMAJA\r\nDOSIS 1"                         
[32] "REMAJA\r\nDOSIS 2"                         
[33] "REMAJA\r\nDOSIS 3"                         
[34] "REMAJA TOTAL\r\nVAKSIN DIBERIKAN"          </code></pre>
</div>
</div>
<table class="table">
<thead>
<tr class="header">
<th>Name</th>
<th>Translation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>KODE KELURAHAN</td>
<td>Village Code</td>
</tr>
<tr class="even">
<td>WILAYAH KOTA</td>
<td>City Region</td>
</tr>
<tr class="odd">
<td>KECAMATAN</td>
<td>Sub-District</td>
</tr>
<tr class="even">
<td>KELURAHAN</td>
<td>Ward</td>
</tr>
<tr class="odd">
<td>TOTAL VAKSIN\r\nDIBERIKAN</td>
<td>Total Vaccination</td>
</tr>
<tr class="even">
<td>BELUM VAKSIN</td>
<td>Not Vaccinated</td>
</tr>
</tbody>
</table>
</section>
<section id="mutate-aspatial-data" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="mutate-aspatial-data"><span class="header-section-number">3.2.3</span> Mutate Aspatial Data</h3>
<section id="mutating-using-for-loop" class="level4" data-number="3.2.3.1">
<h4 data-number="3.2.3.1" class="anchored" data-anchor-id="mutating-using-for-loop"><span class="header-section-number">3.2.3.1</span> Mutating using for loop</h4>
<p>As there are 12 data sets, we will use the for loop that mutate, rename and select the fields that we want. The code chunk below does the following:</p>
<ol type="1">
<li>Renames KODE KELURAHAN, WILAYAH KOTA, KECAMATAN, KELURAHAN, TOTAL VAKSIN\r\nDIBERIKAN and BELUM VAKSIN to village_code, city_region, subdistrict, ward, total_vaccination and not_vaccinated respectively by using rename() from the dplyr package</li>
<li>Selects the renamed columns by using select() from the dplyr package</li>
<li>Adds a date column by using mutate() from the dplyr package</li>
</ol>
<p>All the mutated aspatial data frames are then placed into a list</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>list_mth<span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">`</span><span class="at">2021-7</span><span class="st">`</span>,<span class="st">`</span><span class="at">2021-8</span><span class="st">`</span>,<span class="st">`</span><span class="at">2021-9</span><span class="st">`</span>,<span class="st">`</span><span class="at">2021-10</span><span class="st">`</span>,<span class="st">`</span><span class="at">2021-11</span><span class="st">`</span>,<span class="st">`</span><span class="at">2021-12</span><span class="st">`</span>,<span class="st">`</span><span class="at">2022-1</span><span class="st">`</span>,<span class="st">`</span><span class="at">2022-2</span><span class="st">`</span>,<span class="st">`</span><span class="at">2022-3</span><span class="st">`</span>,<span class="st">`</span><span class="at">2022-4</span><span class="st">`</span>,<span class="st">`</span><span class="at">2022-5</span><span class="st">`</span>,<span class="st">`</span><span class="at">2022-6</span><span class="st">`</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>date <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"July 2021"</span>, <span class="st">"August 2021"</span>, <span class="st">"September 2021"</span>, <span class="st">"October 2021"</span>, <span class="st">"November 2021"</span>, <span class="st">"December 2021"</span>, <span class="st">"January 2022"</span>, <span class="st">"February 2022"</span>, <span class="st">"March 2022"</span>, <span class="st">"April 2022"</span>, <span class="st">"May 2022"</span>, <span class="st">"June 2022"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>lists <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)){</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  lists[[i]]<span class="ot">&lt;-</span> list_mth[[i]] <span class="sc">%&gt;%</span> </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">village_code=</span><span class="st">`</span><span class="at">KODE KELURAHAN</span><span class="st">`</span>, </span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">city_region =</span><span class="st">`</span><span class="at">WILAYAH KOTA</span><span class="st">`</span>, </span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">subdistrict=</span><span class="st">`</span><span class="at">KECAMATAN</span><span class="st">`</span>, </span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">ward=</span><span class="st">`</span><span class="at">KELURAHAN</span><span class="st">`</span>, </span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">total_vaccination=</span> <span class="st">`</span><span class="at">TOTAL VAKSIN</span><span class="sc">\r\n</span><span class="at">DIBERIKAN</span><span class="st">`</span>, </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">not_vaccinated =</span><span class="st">`</span><span class="at">BELUM VAKSIN</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(village_code, city_region, subdistrict, not_vaccinated ,total_vaccination) <span class="sc">%&gt;%</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">date =</span> date[i], </span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">.before=</span><span class="dv">1</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="combine-into-a-single-dataframe-from-a-list-of-dataframes" class="level4" data-number="3.2.3.2">
<h4 data-number="3.2.3.2" class="anchored" data-anchor-id="combine-into-a-single-dataframe-from-a-list-of-dataframes"><span class="header-section-number">3.2.3.2</span> Combine into a single dataframe from a list of dataframes</h4>
<p>Afterwhich, we can use Reduce() and rbind from base R to join all dataframes in the lists as one dataframe.</p>
<p>The code chunk below does this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>aspatial_data <span class="ot">&lt;-</span> <span class="fu">Reduce</span>(rbind, lists)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(aspatial_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,216
Columns: 6
$ date              &lt;chr&gt; "July 2021", "July 2021", "July 2021", "July 2021", …
$ village_code      &lt;chr&gt; NA, "3172051003", "3173041007", "3175041005", "31750…
$ city_region       &lt;chr&gt; NA, "JAKARTA UTARA", "JAKARTA BARAT", "JAKARTA TIMUR…
$ subdistrict       &lt;chr&gt; NA, "PADEMANGAN", "TAMBORA", "KRAMAT JATI", "JATINEG…
$ not_vaccinated    &lt;dbl&gt; 5041111, 13272, 16477, 18849, 5743, 15407, 12503, 11…
$ total_vaccination &lt;dbl&gt; 3877757, 10401, 12520, 8945, 4454, 11342, 9125, 1365…</code></pre>
</div>
</div>
<p>We can see from the output that we have the columns that we want in its new name and having 3216 rows.</p>
<p>From the glimpse output, we can see that there are NA values inside the dataframe. If you View the original individual files, you will notice that there will be a row that calculates the total of a respective column.</p>
</section>
<section id="final-steps-to-take" class="level4" data-number="3.2.3.3">
<h4 data-number="3.2.3.3" class="anchored" data-anchor-id="final-steps-to-take"><span class="header-section-number">3.2.3.3</span> Final steps to take</h4>
<p>So these are the steps to take,</p>
<ol type="1">
<li>Remove the NA rows in the dataframe</li>
<li>Filter out the outer islands
<ul>
<li>You will notice from the output of the code chunk below that outer islands is categorised as KAB.ADM.KEP.SERIBU</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(aspatial_data<span class="sc">$</span>city_region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA                   "JAKARTA UTARA"      "JAKARTA BARAT"     
[4] "JAKARTA TIMUR"      "JAKARTA SELATAN"    "JAKARTA PUSAT"     
[7] "KAB.ADM.KEP.SERIBU"</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Add in total population and vaccination rate columns
<ul>
<li>Formula:</li>
</ul></li>
</ol>
<p>The code chunk below does this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>aspatial_data <span class="ot">&lt;-</span> aspatial_data <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.exclude</span>() <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(city_region <span class="sc">!=</span> <span class="st">"KAB.ADM.KEP.SERIBU"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_population =</span> total_vaccination <span class="sc">+</span> not_vaccinated, <span class="at">vaccination_rate =</span> total_vaccination<span class="sc">/</span>total_population)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="combining-geospatial-and-aspatial-together" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="combining-geospatial-and-aspatial-together"><span class="header-section-number">3.3</span> Combining Geospatial and Aspatial together</h2>
<p>Do note that the names for aspatial_data and geoDKI are of different names. Ensure that when using left_join() from the dplyr package, we insert the argument by = c(). This will join using village_code</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>vaccination <span class="ot">&lt;-</span> <span class="fu">left_join</span>(aspatial_data, geoDKI, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"village_code"</span> <span class="ot">=</span> <span class="st">"KODE_DESA"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>vaccination <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(vaccination) <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.factor</span>(date))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="choropleth-mapping-and-analysis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Choropleth Mapping and Analysis</h1>
<section id="visualizing-the-data" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="visualizing-the-data"><span class="header-section-number">4.1</span> Visualizing the data</h2>
<section id="r-shiny" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="r-shiny"><span class="header-section-number">4.1.1</span> R Shiny</h3>
<p>Something extra to this TakeHome Assignment will be the use of the ShinyApp. This is a short introduction as to how Rshiny works:</p>
<ol type="1">
<li>Define the UI:
<ul>
<li><p>You will have an input and in this case, we will use selectInput(“dates”, “Pick a month”, date, selected = “July 2021”,multiple = FALSE).</p>
<ul>
<li><p>“dates”: This is the variable name to call into the output portion in the server</p></li>
<li><p>“Pick a month”: This is a text under the user interface to ask the user to pick a choice</p></li>
<li><p>date: This is the vector of choices that they can pick from.</p></li>
<li><p>selected = “July 2021” : This sets the choice “July 2021” as the default when starting up the app</p></li>
<li><p>multiple = FALSE : Prevents the user from picking multiple options and can only choose 1</p></li>
</ul></li>
</ul></li>
<li>Define Server:
<ul>
<li>This is where tmap is used and calls upon the variable name defined in UI which is “dates”.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(shiny)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>date <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"July 2021"</span>, <span class="st">"August 2021"</span>, <span class="st">"September 2021"</span>, <span class="st">"October 2021"</span>, <span class="st">"November 2021"</span>, <span class="st">"December 2021"</span>, <span class="st">"January 2022"</span>, <span class="st">"February 2022"</span>, <span class="st">"March 2022"</span>, <span class="st">"April 2022"</span>, <span class="st">"May 2022"</span>, <span class="st">"June 2022"</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the UI</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>ui <span class="ot">&lt;-</span> <span class="fu">fluidPage</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">selectInput</span>(<span class="st">"dates"</span>, <span class="st">"Pick a month"</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>              date, <span class="at">selected =</span> <span class="st">"July 2021"</span>,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">multiple =</span> <span class="cn">FALSE</span>),</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tmapOutput</span>(<span class="st">"my_map"</span>)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the server</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>server <span class="ot">&lt;-</span> <span class="cf">function</span>(input, output) {</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Render the tmap in the output element</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>  output<span class="sc">$</span>my_map <span class="ot">&lt;-</span> <span class="fu">renderTmap</span>({</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>    a <span class="ot">&lt;-</span> vaccination <span class="sc">|&gt;</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(date <span class="sc">==</span> input<span class="sc">$</span>dates)</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(a) <span class="sc">+</span></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"vaccination_rate"</span>,</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span><span class="st">"Blues"</span>)</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the app</span></span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a><span class="fu">shinyApp</span>(ui, server)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Refer to visual plot : <a href="https://junhaoteo.shinyapps.io/Take-Home_Ex02/">ShinyApp</a></p>
<p>Note: There are many ways to create and design the shiny app, under the user interface. One example is using a sliderInput() to let the user their zoom level. This can be found under R shiny documentation.</p>
</section>
<section id="tmap-visualization" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="tmap-visualization"><span class="header-section-number">4.1.2</span> Tmap Visualization</h3>
<p>Considering we have 12 months of Tmap visualization to do, it would be better to create a tmap function.</p>
<p>The code chunk below first filters out vaccination dataframe into their respective months and then inputs the filtered dataframe into the tm_shape().</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>graphing <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> vaccination <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(date <span class="sc">==</span> x)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(a) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"vaccination_rate"</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">6</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Vaccination Rate"</span>) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="fu">paste</span>(x),</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"left"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.8</span>, </span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.8</span>,</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span><span class="fl">0.2</span>)</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will split the plots into 2 code chunks to reduce the number of graphs in a single output for a clearer view.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">graphing</span>(<span class="st">"July 2021"</span>),</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"August 2021"</span>),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"September 2021"</span>),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"October 2021"</span>),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"November 2021"</span>),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"December 2021"</span>),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">graphing</span>(<span class="st">"January 2022"</span>),</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"February 2022"</span>),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"March 2022"</span>),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"April 2022"</span>),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"May 2022"</span>),</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>             <span class="fu">graphing</span>(<span class="st">"June 2022"</span>),</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To visualize the data, we can just create a gif, compiled by all the plots made above.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/7bmx3b.gif" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Likewise, this can be done on Rshiny app but this will be covered on a later date when I have attended the Rshiny workshop. :)</p>
</section>
</section>
<section id="spatial-patterns-observed-200words" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="spatial-patterns-observed-200words"><span class="header-section-number">4.2</span> Spatial Patterns observed (200words)</h2>
</section>
</section>
<section id="local-gi-analysis" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Local Gi* Analysis</h1>
<p>To bring you back, here is the task assigned in this section:</p>
<ul>
<li><p>Compute local Gi* values of the monthly vaccination rate,</p></li>
<li><p>Display the Gi* maps of the monthly vaccination rate. The maps should only display the significant (i.e.&nbsp;p-value &lt; 0.05)</p></li>
<li><p>With reference to the analysis results, draw statistical conclusions (not more than 250 words)</p></li>
</ul>
<section id="computing-contiguity-spatial-weights" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="computing-contiguity-spatial-weights"><span class="header-section-number">5.1</span> Computing Contiguity Spatial Weights</h2>
<p>Before we can compute the global spatial autocorrelation statistics, we need to construct the spatial weights of the study area.</p>
<p>Spatial weights: Used to define the neighbourhood relationships between geographical units in the study area.</p>
<p>By using the poly2nb() of spdep package, we can compute the contiguity weight matrices for the study area.</p>
<p>As we are dealing with 12 different months of vaccination rates, we will have to filter the dataframe to their respective months and calculate their respective weights. Here, we will be using the ROOK mode and thus the argument: queen =FALSE. The code chunk below is a filters to the selected month and then calculate their weights by using poly2nb() of the spdep package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>month <span class="ot">&lt;-</span> vaccination <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(date <span class="sc">==</span> <span class="st">"July 2021"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>wm <span class="ot">&lt;-</span><span class="fu">poly2nb</span>(month,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">queen =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 261 
Number of nonzero links: 1488 
Percentage nonzero weights: 2.184348 
Average number of links: 5.701149 
Link number distribution:

 2  3  4  5  6  7  8  9 11 
 5 11 45 57 68 40 25  9  1 
5 least connected regions:
35 88 155 220 255 with 2 links
1 most connected region:
110 with 11 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 261 area units in DKI Jakarta and the most connected area unit has 11 neighbours.</p>
</section>
<section id="row-standardised-weights-matrix" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="row-standardised-weights-matrix"><span class="header-section-number">5.2</span> Row-standardised weights matrix</h2>
<p>Moving on, we will need to assign weights to each neighbouring polygon.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>rswm <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">style =</span> <span class="st">"W"</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>rswm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 261 
Number of nonzero links: 1488 
Percentage nonzero weights: 2.184348 
Average number of links: 5.701149 

Weights style: W 
Weights constants summary:
    n    nn  S0       S1       S2
W 261 68121 261 96.30166 1066.273</code></pre>
</div>
</div>
</section>
<section id="moran-i-test" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="moran-i-test"><span class="header-section-number">5.3</span> Moran I Test</h2>
<p>To run all 12 months local Gi, we will create a function calculates the weights, assignes them to each neighbouring polygon and then to calculate the statistical values. When calculating each month, we want to ensure that the dataframe used is the correct on and thus the reason why we put them together. The code chunk below features a function that takes the month as an input and returns the Moran’s I test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>localmoran_test <span class="ot">&lt;-</span> <span class="cf">function</span>(mth){</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  month <span class="ot">&lt;-</span> vaccination <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(date <span class="sc">==</span> mth)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  wm_q <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(month,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">queen =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  rswm_q <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">style =</span> <span class="st">"W"</span>,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  fips <span class="ot">&lt;-</span> <span class="fu">order</span>(month<span class="sc">$</span>vaccination_rate)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  localMI <span class="ot">&lt;-</span> <span class="fu">localmoran</span>(month<span class="sc">$</span>vaccination_rate, rswm_q)</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(localMI)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below applies localmoran_test() to a list of dates and output the data into a list. Do note that date is a list containing “July 2021”, “August 2021”, … , “June 2020”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>localmoran_test_stat <span class="ot">&lt;-</span> <span class="fu">lapply</span>(date, <span class="at">FUN =</span> localmoran_test)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(localmoran_test_stat[[<span class="dv">1</span>]], <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Ii          E.Ii      Var.Ii       Z.Ii Pr(z != E(Ii))
1 -0.07681186 -6.016665e-05 0.001690837 -1.8665392     0.06196597
2  0.15483408 -2.134499e-04 0.013763342  1.3216087     0.18629847
3  1.47904197 -1.296001e-02 0.825013181  1.6426270     0.10046013
4  0.13419598 -1.014655e-04 0.003695197  2.2092707     0.02715582
5  0.09070897 -4.669042e-04 0.030098555  0.5255416     0.59920673
6 -0.10630834 -5.527985e-04 0.017537917 -0.7985721     0.42453859</code></pre>
</div>
</div>
<p>The output of the code chunk below follows the same sequence as date where localmoran_test_stat[[1]] refers to “July 2021” and localmoran_test_stat[[12]] refers to “June 2022”.</p>
<p>The code chunks below creates a function that binds the filtered dataframe and the localmoran_test_stat together and loops it into a list called vac.localMI.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>localMI<span class="ot">&lt;-</span> <span class="cf">function</span>(mth,x){</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  month <span class="ot">&lt;-</span> vaccination <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(date <span class="sc">==</span> mth)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  vac_mth.local.MI <span class="ot">&lt;-</span> <span class="fu">cbind</span>(month, localmoran_test_stat[[x]]) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">Pr.Ii=</span><span class="st">`</span><span class="at">Pr.z....E.Ii..</span><span class="st">`</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(vac_mth.local.MI)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>vac.localMI <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>){</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  vac.localMI[[i]] <span class="ot">&lt;-</span> <span class="fu">localMI</span>(date[i], i)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then visualize the date below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>localMI_Map <span class="ot">&lt;-</span> <span class="cf">function</span>(MI){</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(MI) <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="cn">Inf</span>),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"-Blues"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local moran p-value"</span>) <span class="sc">+</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(<span class="fu">localMI_Map</span>(vac.localMI[[<span class="dv">1</span>]]),</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>             <span class="fu">localMI_Map</span>(vac.localMI[[<span class="dv">2</span>]]),</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">localMI_Map</span>(vac.localMI[[<span class="dv">3</span>]]),</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>             <span class="fu">localMI_Map</span>(vac.localMI[[<span class="dv">4</span>]]),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>             <span class="fu">localMI_Map</span>(vac.localMI[[<span class="dv">5</span>]]),</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>             <span class="fu">localMI_Map</span>(vac.localMI[[<span class="dv">6</span>]]),</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="statistical-conclusion-not-more-than-250words" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="statistical-conclusion-not-more-than-250words"><span class="header-section-number">5.3.1</span> Statistical Conclusion (Not more than 250words) :</h3>
</section>
<section id="section" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="section"><span class="header-section-number">5.3.2</span> </h3>
<div class="cell">

</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>